# Test Replay Buffer

In [1]:
%run replay_buffer

## Initialization

In [2]:
frameShape = (2, 3) # small dummy shape
foo = ReplayBuffer(3, frameShape)

In [3]:
foo

self.size = 3
self.shape = (2, 3)
self.index = 0

## storeTransition

Overwriting the oldest entries takes place.

In [21]:
for i in range(0, 5):
    phi = torch.randn(frameShape)
    action = torch.randint(high = 4, size = (1,)) # must be a tuple
    reward = torch.randint(high = 100, size = (1,))
    nextState = torch.randn(frameShape)
    transition = (phi, action, reward, nextState)
    foo.storeTransition(transition)

    print(f"---\n{foo.index = }\nReward:\t{foo.reward}")

---
foo.index = 0
Reward:	tensor([93., 63., 12.])
---
foo.index = 1
Reward:	tensor([54., 63., 12.])
---
foo.index = 2
Reward:	tensor([54.,  6., 12.])
---
foo.index = 0
Reward:	tensor([54.,  6., 59.])
---
foo.index = 1
Reward:	tensor([19.,  6., 59.])


## sample

Proof of principle.

In [9]:
asdf = torch.randn(5)
asdf

tensor([ 0.6691, -0.0332,  1.3066,  0.4105, -1.0266])

In [6]:
asdf2 = torch.randperm(n = 5)
asdf2

tensor([2, 3, 4, 1, 0])

In [7]:
asdf[asdf2]

tensor([-2.2256, -0.6780,  0.1976, -0.8688, -0.0258])

Use of sample.

In [17]:
phi, action, reward, nextState = foo.sample(1)
labels = "phi,action,reward,nextState"

for i,j in zip([phi, action, reward, nextState], labels.split(',')) :
    print(j, i)

phi tensor([[[-0.9590, -1.9910,  0.4891],
         [-0.3414, -1.6896, -0.0722]]])
action tensor([0.])
reward tensor([65.])
nextState tensor([[[-0.5649, -1.7235,  1.0847],
         [ 1.6714, -0.5161,  2.6011]]])
