# Test Replay Buffer

In [1]:
%run ../replay_buffer

## Initialization

In [2]:
frameShape = (2, 3) # small dummy shape
foo = ReplayBuffer(3, frameShape)

In [3]:
foo

self.size = 3
self.shape = (2, 3)
self.index = 0

## storeTransition

Overwriting the oldest entries takes place.

In [4]:
for i in range(0, 5):
    phi = torch.randn(frameShape)
    action = torch.randint(high = 4, size = (1,)) # must be a tuple
    reward = torch.randint(high = 100, size = (1,))
    nextState = torch.randn(frameShape)
    transition = (phi, action, reward, nextState)
    foo.storeTransition(transition)

    print(f"---\n{foo.index = }\nReward:\t{foo.reward}")

---
foo.index = 1
Reward:	tensor([39.,  0.,  0.])
---
foo.index = 2
Reward:	tensor([39.,  8.,  0.])
---
foo.index = 0
Reward:	tensor([39.,  8., 13.])
---
foo.index = 1
Reward:	tensor([28.,  8., 13.])
---
foo.index = 2
Reward:	tensor([28., 47., 13.])


## sample

Proof of principle.

In [5]:
asdf = torch.randn(5)
asdf

tensor([ 0.0866, -1.4963, -1.3389,  1.1942, -0.4962])

In [6]:
asdf2 = torch.randperm(n = 5)
asdf2

tensor([2, 3, 1, 4, 0])

In [7]:
asdf[asdf2]

tensor([-1.3389,  1.1942, -1.4963, -0.4962,  0.0866])

Use of sample.

In [8]:
phi, action, reward, nextState = foo.sample(1)
labels = "phi,action,reward,nextState"

for i,j in zip([phi, action, reward, nextState], labels.split(',')) :
    print(j, i)

phi tensor([[[-2.0404, -0.1872, -1.2621],
         [-0.3393, -0.3620, -1.0831]]])
action tensor([1.])
reward tensor([28.])
nextState tensor([[[-1.0990, -0.9698, -0.3921],
         [-0.8185, -0.2679, -0.4961]]])
